package com.hqa.backend.dto;

public enum ErrorCode {
    INVALID_REQUEST,
    INTERNAL_ERROR,
    UNAUTHORIZED,
    INVALID_CREDENTIALS,
    USER_ALREADY_EXISTS,
    USER_INACTIVE,
    KIS_SECRET_NOT_CONFIGURED,
    SURVEY_NOT_FOUND,
    SERVICE_UNAVAILABLE,
    CHART_LOAD_FAILED,
    CHART_API_NOT_CONFIGURED,
    CHART_NO_DATA,
    ANALYSIS_FAILED,
    ANALYSIS_NOT_FOUND,
    STOCK_NOT_FOUND,
    STOCK_INVALID_CODE
}
