package com.hqa.backend.dto;

public enum ErrorCode {
    INVALID_REQUEST,
    INTERNAL_ERROR,
    SERVICE_UNAVAILABLE,
    CHART_LOAD_FAILED,
    CHART_API_NOT_CONFIGURED,
    CHART_NO_DATA,
    ANALYSIS_FAILED,
    ANALYSIS_NOT_FOUND,
    STOCK_NOT_FOUND,
    STOCK_INVALID_CODE
}
